name: Build thedmdim/llama-telegram-bot:latest and push to hub.docker.com

on:
  push:
    branches:
      - "master"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: thedmdim/llama-telegram-bot:latest